# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

**Note: we are using 0 to represent heads, and 1 to represent tails.**

In [1]:
# import numpy
import numpy as np


### 1. Two fair coin flips produce exactly two heads

**Mathematically**
`p(two Heads)= (2!/(2!*0!))*0.5*0.5= 0.25`

In [2]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads, since the head is represnted by zero
(test_sums == 0).mean()

0.249889

In [3]:
print(tests)

[[0 1]
 [0 0]
 [0 0]
 ...
 [1 0]
 [1 1]
 [1 1]]


In [4]:
print(test_sums)

[1 0 0 ... 1 2 2]


### 2. Three fair coin flips produce exactly one head

**Mathematically** \
`p(one Head)= (3!/(1!*2!))*0.5*0.5*0.5= 0.375`

In [5]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
# to have one head this means the other two flips are tails. since the tail 
# is represented by one, then to have one head and two tails the sum must represent 2
(test_sums == 2).mean()

0.375052

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

**Mathematically** \
`p(one Head)= (3!/(1!*2!))*0.6*0.4*0.4= 0.288`

In [6]:
# simulate 1 million tests of three biased coin flips

tests = np.random.choice([0,1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.288191

### 4. A die rolls an even number

**Mathematically** \
`p(even number)= 3*1/6= 0.5`

In [18]:
# simulate 1 million tests of one die roll
tests = np.random.randint(1,7, size=(int(1e6)))
                          
print(tests[:20])
                          
# proportion of tests that produced an even number
(tests %2 == 0).mean()

[1 4 1 5 5 4 5 6 1 6 1 4 6 6 6 6 3 5 4 5]


0.498949

### 5. Two dice roll a double

**Mathematically** \
`p(double)= 6*(1/6)*(1/6) = 0.167`

In [19]:
# simulate the first million die rolls
first = np.random.randint(1,7, size=(int(1e6)))

# simulate the second million die rolls
second = np.random.randint(1,7, size=(int(1e6)))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.166448